language: python
dist: xenial
addons:
  snaps:
  - name: aws-cli
    confinement: classic
    channel: latest/edge
services:
- docker
before_install:
- pip install flake8
- npm install -g eslint stylelint
script:
- flake8 moderator
- eslint 'moderator/moderate/static/js/*.js'
- stylelint 'moderator/moderate/static/css/*.css'
- docker build . -t "$ECR:$TRAVIS_COMMIT"
before_deploy:
- eval $(aws ecr get-login --no-include-email --region us-west-2)
deploy:
  provider: script
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^(master|prod)$"
  script: docker push "$ECR:$TRAVIS_COMMIT"
env:
  global:
  - secure: "VSt7rF0PCNcdU6Axct8w1qttKyMpWvaIhTy7H084mj29nXPrSM3GOfRy8r/pSmaFgRjo7AiD9Oi5ZE79RwCn/O+q0Bfftua0JL+SXI9XWEAhTlvqJM+EtXLNBP+B9AyssQxOHAp9lgCPaiZEb+ymZfEbZZq9f/UK03PC53b4R5M="
  - ECR="$AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/moderator"
