# Trigger a commit
language: python
dist: trusty
sudo: false
before_install:
  - pip install flake8
  - npm install -g eslint stylelint
script:
  - flake8 moderator
  - eslint 'moderator/moderate/static/js/*.js'
  - stylelint 'moderator/moderate/static/css/*.css'
