language: python

dist: xenial
addons:
  snaps:
    - aws-cli

services:
 - docker

before_install:
 - pip install flake8
 - npm install -g eslint stylelint
script:
 - flake8 moderator
 - eslint 'moderator/moderate/static/js/*.js'
 - stylelint 'moderator/moderate/static/css/*.css'
 - docker build . -t "$ECR:$TRAVIS_COMMIT"

before_deploy:
 - eval $(aws ecr get-login --no-include-email --region us-west-2)
deploy:
 - docker push "$ECR:$TRAVIS_COMMIT"

env:
  global:
  - secure: alnR1tayq6SWkOdg3n02ZxfRm0zbj9HObMIKn71AX/lBZkEvfI1N77I1gl+D3NzfZLJEXzHMNJfUlqi+Ygl+CGGbwCaIafAwmRs0vHwfgKv3ZI+wmk1LMvq5Hor4B+W67A4d2POk47IxDhPJcZ/nKEftfvbVKH7XPZGG+7dpPRTrahr6aWy+NXJCJGp6BqPxHaNhaxtpYwH+AZny4Fo3LD1DCzdBB2C8IbcN/4eXw+3b+m4rJ4lLQHo1VOoA/H6TRl+Dj8UliIQtghsghquc5t78vOPe9YixlkZJeJamuLwownjMdJo37p4rxR0UU4sKxrT5WuCIwIGBcOBGFDsr6IqyPhc7cbwMSd8SwWCXjEwLu6CHs5PQnNv+kzUYY/Q9jw3SUXVJ3belX1ap3YLmGiuJYwdNL1h4uofdJyrw0++1GWEFfrtBWUXcUsBetSVgmJC5wlf1dKxTvDEIx2ZF0l15jWAzdJg27N8CJqQptR+VJgJveLsKN/pZOgdzTZAUisBGcPWdFGnIKsqg1BCdsYBvJx2+Snb1EVyhiQ3vhOSg2DipZ+mT/m3ApEWH8bcO9+vH0IimVVoLDZOh5W/AY3fUtW/iQewd+dpMTjN03oceTlGdDksJAk32lQSnf91TGEdaZy+eyjUJZxOuki9NXc/1a5Rff5bm4JJKHS5bh34=
  - secure: otSUUS0D9xHf5qZiPv1vvHxztzvMq+vrFTNE+bCR+kKbwdxw7JcKJqNrS1Y7BSlsxPExP6cg+YlqpAMrREemqHU40Ts69YTR2uMDbHPEQHhU2Ei8CQR3f4TLpGwWB6JGmsF4mXryl0IyRAwsFewgOAcyySrWFjAUgPJqwv2WKyxTDK/fzTalLRkWiBLG46jiMOnHSdxtIwDAOXMXMyGgzGJ873+JmezEDFKrLrDtiuyNuugZWDobYMqgZZ2jL6PBhmJwiKhys3In2HBw2aDeIXDRL9rHACl6srLs/+DuOXWO9IQY6BJuqXc8uJHzS1On2fJGt4+cC2HbjhkEl5NrVkVNeCY/4syruuX+aZVXp0C2dPLFMhrDQP02idaKE2aqGtZ2erzQVn1/PrOpW21wMVI21tlEHhJ/8fXaE+NsOhz2imdXciLk2DbBjSFru5PAS/A6vxbeVTroKDeJipTKRF+XQjt51iV4gospbYfjgYpqhUPqICC+tUSk2ZqbbJWyNgE3Z/pkpFUdo42hYlJ9YPOonDB/UqC/WtLlmRi1I+jPyOEcw3HxI2FgmVQFBiGKrHchECr+DUlBu+wvKcpoljJEt1DqwzMFzrrqhVlXustw1jajdOM/anMPWtHF3Esqsi6tirgwqDabskWRjAw/dwZXy/fwHfweSJJA62lkq6Q=
  - secure: ol+plznHz48j8hb0vqh764e3lEGD19glQFsv6ZTy1VPUviaFEODNbt6xhs/m8wI/qU/xTp9w8RVpMoYyYKcJ+W6a8AX7F/4oWavBqxwXYk5imrBKjxQ5R6JYl3LsNRhxoqRZCfIZad7zdfXzSj5mJVb9nO15Daiq7qIZjpfx9uKT37PtWMRVRzsLplgODlHHFFAo3WY2ZOD3BK0DOfNIsxKa3of6n6ALNpLNSgOuCtFsBmvIKN1VY9drWaDpepLUczs8vLJlua8nB1RGVYF+bgOukZJGTyAt5OeROpeXUs1w7rdUxMk5JgkeqGhoD2z1XC4EH/h8km7/QFaP7gy9YR4DupfSUZWev+7W136G2XMQUPJ8b1zy++npj4vps9liUv3G0MO+ASX1pcsedKTJSyUAs0DEAYkpZfAGkquA4IrKlkOivQ6T3kyOqtmPXVNdVSquUpEG2oFamWL7qyJ+YqufegSyTw2bkmSVEGhWUBJsPqyYZVAN9PQJZE3LR91iJnuao6EbAfmLtWwK2qqkL4qVxAhL2MvyM9vcR062HkFuGld3Tt5UssxIbf4RXUcRMnACiycS0h9b81beRY/Ttab1ewV/c51PlIqam+UAXqHW/ez4a/2g6mfbF6/oO/i2H2mbSD9cslZGEcpLg3x6fONf0pSbL8xgG0mfZPw8xos=
  - ECR="$AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/moderator"
